apiVersion: apps/v1
kind:  Deployment
metadata:
  name: myapp
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        env: demo
      name: myapp
    spec:
      containers:
      - image: nginx:1.23.4-alpine
        name: myapp
        ports:
        - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      env: demo